apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-79-tenant/load-app-cce53101-db1b-4e6b-81d6-44e31e34020a/devfile-sample-code-with-quarkus@sha256:b05bea4a8077e0471164ed6ad1fac11018994e1fc14a164b2ae38b077381f081
        name: my-java-quarkus
        resources: {}
status: {}
